### ISSUE TITLE
Slight conflict with existing/external overwrites/superFuncs

### ISSUE THREAD

**Issue by alfalfa6945** [LoogleCZ/FS17-FillableConfiguration#2]
If the script is used on a vehicle/implement with the "Cover" specialization (for instance), there will be a slight conflict between FillableConfiguration and Cover due to Cover not being able to supersede the addFillTrigger(trigger) and removeFillTrigger(trigger) (self.addFillTrigger and self.removeFillTrigger respectively). This, of course, will cause Cover to not be able to auto-open/close the cover(s) of the vehicle/implement when in a fillTrigger. In testing, I've commented out lines 48-49:

`--self.addFillTrigger = Fillable.addFillTrigger;`
`--self.removeFillTrigger = Fillable.removeFillTrigger;`

This restores the functionality of Cover to be able to supersede those functions and operate the cover(s) correctly when in a fillTrigger.

**Comment by LoogleCZ** [comment]
Hi! As soon as possible I will take a closer look at this problem.
I don't know the implementation of cover as I can't get to documentation right now, but maybe if the order of specializations will be different (eg. Cover after FillConf - and fill conf after all other changed specializations) it could work well. But that's just guessing.
Again thanks

**Comment by alfalfa6945** [comment]
Having FillableConfiguration at the end of the specialization list and then having Cover moved to below that works as you thought it would, solves the issue. No worries on when you get a chance to look at this issue, it's a minor issue and you already have a handle on the situation. Thank you for your efforts!
